# Generated by Django 6.0.3 on 2026-04-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_uid', models.CharField(max_length=64, unique=True)),
                ('machine_type', models.CharField(choices=[('bulldozer', 'Buldozer'), ('excavator', 'Excavator'), ('crane', 'Macara'), ('compactor', 'Compactor'), ('grader', 'Greder'), ('loader', 'Incărcător frontal'), ('dumptruck', 'Autobasculantă'), ('piledriver', 'Pilot batere piloți'), ('concrete_pump', 'Pompă beton'), ('other', 'Alt utilaj')], max_length=32)),
                ('machine_id', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('firmware', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['machine_type', 'machine_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tool', 'Sculă / Unealtă'), ('environment', 'Mediu înconjurător'), ('engine', 'Motor'), ('accident_prevention', 'Prevenire accidente'), ('hydraulic', 'Sistem hidraulic'), ('pneumatic', 'Sistem pneumatic'), ('transmission', 'Transmisie'), ('gps', 'GPS / Localizare'), ('system', 'Sistem IoT')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('is_numeric', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='telemetry.sensorcategory')),
            ],
            options={
                'ordering': ['category', 'sensor_id'],
                'unique_together': {('category', 'sensor_id')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=256)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Avertizare'), ('critical', 'Critic'), ('fault', 'Defect'), ('unknown', 'Necunoscut')], default='normal', max_length=16)),
                ('topic', models.CharField(max_length=256)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.sensor')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.machinesystem')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['system', 'sensor', '-received_at'], name='telemetry_s_system__92149e_idx'), models.Index(fields=['received_at'], name='telemetry_s_receive_f5c339_idx'), models.Index(fields=['status'], name='telemetry_s_status_140907_idx')],
            },
        ),
    ]
