# Generated by Django 6.0.3 on 2026-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('proximity', 'Proximity'), ('line', 'Line Following'), ('camera', 'Camera'), ('motor', 'Motor'), ('heartbeat', 'Heartbeat'), ('system', 'System')], max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='normal', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
